INFO 2023-01-13 18:14:06,771 basehttp "GET /logs/ HTTP/1.1" 200 449
ERROR 2023-01-13 18:14:10,728 log Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view students.views.view didn't return an HttpResponse object. It returned None instead.
ERROR 2023-01-13 18:14:10,731 basehttp "GET /index/ HTTP/1.1" 500 64790
DEBUG 2023-01-13 18:14:11,962 autoreload File C:\Users\Admin\AppData\Local\Programs\Python\Python310\Lib\importlib\readers.py first seen with mtime 1659371368.0
DEBUG 2023-01-13 18:14:11,965 autoreload File C:\Users\Admin\AppData\Local\Programs\Python\Python310\Lib\zipfile.py first seen with mtime 1659371368.0
DEBUG 2023-01-13 18:14:11,972 autoreload File C:\Users\Admin\AppData\Local\Programs\Python\Python310\Lib\importlib\_adapters.py first seen with mtime 1659371368.0
DEBUG 2023-01-13 18:14:11,972 autoreload File C:\Users\Admin\AppData\Local\Programs\Python\Python310\Lib\importlib\resources.py first seen with mtime 1659371368.0
DEBUG 2023-01-13 18:14:11,981 autoreload File C:\Users\Admin\Desktop\django_project\env\Lib\site-packages\tzdata\__init__.py first seen with mtime 1642412364.0
DEBUG 2023-01-13 18:14:11,982 autoreload File C:\Users\Admin\AppData\Local\Programs\Python\Python310\Lib\importlib\abc.py first seen with mtime 1659371368.0
DEBUG 2023-01-13 18:14:11,986 autoreload File C:\Users\Admin\Desktop\django_project\env\Lib\site-packages\tzdata\zoneinfo\__init__.py first seen with mtime 1642412364.0
DEBUG 2023-01-13 18:14:11,987 autoreload File C:\Users\Admin\AppData\Local\Programs\Python\Python310\Lib\importlib\_common.py first seen with mtime 1659371368.0
INFO 2023-01-13 18:14:12,560 basehttp "GET /logs/ HTTP/1.1" 200 4362
ERROR 2023-01-13 18:14:55,806 log Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view students.views.view didn't return an HttpResponse object. It returned None instead.
ERROR 2023-01-13 18:14:55,808 basehttp "GET /index/ HTTP/1.1" 500 64790
INFO 2023-01-13 18:15:03,165 basehttp "GET /logs/ HTTP/1.1" 200 6432
ERROR 2023-01-13 18:15:18,993 log Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view students.views.view didn't return an HttpResponse object. It returned None instead.
ERROR 2023-01-13 18:15:18,995 basehttp "GET /index/ HTTP/1.1" 500 64790
